name: dataset_mobile
description: Mobile client for DataSet crowdsourced visual data platform.
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.3.0
  image_picker: ^1.0.7
  path: ^1.8.3
  mime: ^1.0.5
  permission_handler: ^11.3.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
